### ISSUE TITLE
MultipleInvalid: length of value must be at least 1 for dictionary value @ data['composite']['trackers']

### ISSUE THREAD

**Issue by Mariusthvdb** [pnbruckner/ha-composite-tracker#57]
sorry to report a breaking error in the 3.0.0b1 prerelease. After updating a restart wont go past this:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 221, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/runner.py", line 188, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 147, in async_setup_hass
    config_dict = await conf_util.async_hass_config_yaml(hass)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config.py", line 501, in async_hass_config_yaml
    await merge_packages_config(hass, config, core_config.get(CONF_PACKAGES, {}))
  File "/usr/src/homeassistant/homeassistant/config.py", line 1078, in merge_packages_config
    merge_list = _identify_config_schema(component) == "list"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config.py", line 976, in _identify_config_schema
    default_value = module.CONFIG_SCHEMA({module.DOMAIN: key.default()})[
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: length of value must be at least 1 for dictionary value @ data['composite']['trackers']
```

**Comment by pnbruckner** [comment]
The 3.0.0b0 release notes specifically mention this. (Well, they do now. It already said trackers removed from YAML will be removed from the system. I just added a note that the `trackers` option must contain at least one entry.) Also, note that the 2.8.4 doc page has said for a long time about the `trackers` option: "NOTE: Once legacy support is removed, this variable, with at least one entry, will become required."

**Comment by Mariusthvdb** [comment]
guess no need to fully copy what I said in [the community](https://community.home-assistant.io/t/composite-device-tracker-platform/67345/544?u=mariusthvdb) before I read this now.

suffice to say I still have 3 full trackers with more than 1 entity_id configured in yaml.
